### ISSUE TITLE
requesting a random generator - mini game

### ISSUE THREAD

**Issue by Micr0Bit** [ihptru/orabot#79]
like a "coin toss" ... where orabot just spits out "head" or "tail"
sometime you just want a fair "random" decision ... for example : whos gonna pick the next map/mate/options ? which team can choose his spots (side) first ? ... 

theres various reasons to have a random generator ... and i want it for orabot -> irc 
this might come in handy in the next release , when we do have our IRC - lobby implementation
could look like ;
________________________________________
hamb : call it
Microbit: head
hamb : ]coin
orabot : coin shows tail   (<--- random ...) 
hamb : MicroBit lost ... so i can choose the next map we play
_________________________________________
could also go for a different minigame ... the coin-toss is just a example

**Comment by ihptru** [comment]
also look into ]randomteam : https://github.com/ihptru/orabot/blob/master/commands/randomteam.py
and ]vote : https://github.com/ihptru/orabot/blob/master/commands/voting.py

**Comment by Micr0Bit** [comment]
nice work @ihptru
